apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cloudnative-pg
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - cluster: cloudnative-pg
            url: https://kubernetes.default.svc
            repo: https://cloudnative-pg.github.io/charts
            chart: cloudnative-pg
            targetRevision: 0.20.0
  template:
    metadata:
      name: "{{cluster}}"
    spec:
      project: default
      source:
        repoURL: https://cloudnative-pg.github.io/charts
        chart: "{{chart}}"
        targetRevision: "{{targetRevision}}"
      destination:
        server: "{{url}}"
        namespace: cloudnative-pg
      syncPolicy:
        automated:
          prune: false
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
