apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: argocd-allow
  namespace: argocd
spec:
  podSelector: {}
  policyTypes:
    - Ingress
  ingress:
    - from:
        - ipBlock:
            cidr: 192.168.3.0/24
