apiVersion: v1
kind: Secret
metadata:
  name: pg-user-secret
  namespace: postgres
type: Opaque
data:
  username: ZXhhbXBsZS1taXNza2V5LXVzZXI= # example-misskey-user
  password: ZXhhbXBsZS1taXNza2V5LXBhc3M= # example-misskey-pass
